### PR TITLE
Add wildcard origin matching and manual reply function binding

### LINKED ISSUE #5: No option for manually calling reply function in pm.bind
It is currently not possible to manually call the method causing a reply message to be sent in a function bound in pm.bind.

This could be very useful when the function bound by pm.bind performs an asynchronous operation, and such cannot reply straightaway.

Could be implemented as such:
pm.bind_manual(type, fn, [origin], [hash])
And that fn then gets called with (data, callback), where fn calls callback when it has completed doing its job

### PR DESCRIPTION
**Pull request by jonhoo**
Fixes #5, #6, #8 and #9

### CODE REVIEW

**Comment by daepark** [comment]
Thanks. I will take a look at your patches and merge them in

**Comment by jonhoo** [comment]
Any progress on merging these commits?

**Comment by daepark** [comment]
Hi Jon,

Sorry, I was away for vacation for the past month.
1. Regarding "*" origin, I've submitted your change and also it also
   works when using hash (#) messages.
2. The async responses is a great idea, but I would like to NOT use a
   different bind method (bind_c) but rather use the same bind with
   different options?? If you can do this it would be great!
3. My try/catch thing /is a little overkill, but I wanted a way to
   call the requester's error handler for ANY errors. Maybe I can just
   re-throw the exception if an errback is not defined?

Anyhow, I've now also added qunit tests for same origin
(test/test.html) and cross origin (test/test-x.html).
If you can add tests along with your fixes/features, that would be great!

-dae

On Tue, Nov 8, 2011 at 12:27 AM, Jon Gjengset
reply@reply.github.com
wrote:

**Comment by jonhoo** [comment]
Those commits fix your second and third point from above.
I'm a bit short on time right now, so I don't have the time to implement testing code.
Might do it later if I get the time and don't forget.

**Comment by jonhoo** [comment]
Any ETA on the merging of this pull request?

**Pull request merged**
